### ISSUE TITLE
Hook up CI

### ISSUE THREAD

**Issue by arfon** [spacetelescope/notebooks#1]
> These notebooks are also under continuous integration to ensure that astronomers using these notebooks have a high level of confidence that they will work.

This statement should be made true. 

Suggested approach: copy what they're doing with the [Astropy tutorials](https://github.com/astropy/astropy-tutorials/blob/master/.travis.yml)

**Comment by pllim** [comment]
Isn't this done?

**Comment by arfon** [comment]
Closing this as it's shipped.
