### ISSUE TITLE
Changes needed in DrizzlePac Initialization notebook

### ISSUE THREAD

**Issue by samanthalh** [spacetelescope/notebooks#104]
These changes are to address issues from help desk ticket INC0139608:

In the Required Software section:
1) Add a warning at the beginning (in a color box like the other warnings) that while the notebooks are not tutorials for conda and python, all the steps needed for DrizzlePac are explained. 
2) In that warning, add another link to the astroconda documentation: https://astroconda.readthedocs.io/en/latest/getting_started.html
3) In that warning, add a link to the python starting guide: https://www.python.org/about/gettingstarted/
4) Add text explaining that conda update should be run even with a new conda installation. 
5) Change "source activate/deactivate" to "conda activate/deactivate" and explain that this is new in the latest conda version. 

In the Reference Files section:
1) Explicitly state that DrizzlePac, not just the instrument calibration pipelines, need access to the reference files. 
2) Add text explaining how often reference files need to be downloaded (ie, do the reference files change in a way that requires frequent repetition of this step?)

**Comment by catherine-martlin** [comment]
New tickets - INC0142176 and INC0142177 - reference some out of date links that should be updated.

**Comment by catherine-martlin** [comment]
Hey @samanthalh - I'm working on some of these updates now. For the reference file section do you have an idea of what I should say for number 2? For WFC3 the reference files most important for Drizzle (ie the IDCTAB, NPOLFILE, D2IMFILE) don't change that often. Most changes have happened in the last couple years and we usually inform our users with a newsletter update. Should I just be vague and suggest re-checking periodically? Or would it be better to have a more defined timespan listed?

**Comment by samanthalh** [comment]
Hi @catherine-martlin, I think you're right that we don't deliver those reference files regularly enough to give a time frame. I would just tell them that the deliveries are "infrequent and unpredictable" and tell them how to check if there's a new delivery. The CRDS website has a history page (https://hst-crds.stsci.edu/display_context_history/) and also rerunning the crds.bestrefs command will only download new reference files if they exist, so that's an easy way to check.
