### ISSUE TITLE
can't open notebooks TESS/begginers

### ISSUE THREAD

**Issue by sergiohoyer** [spacetelescope/notebooks#117]
Hi,
I am not able to run/open the notebooks TESS/begginers. For example: 
notebooks/notebooks/MAST/TESS/beginner_astroquery_dv/beginner_astroquery_dv.ipynb

An error occurs in github and when tryin to run it locally.
Cheers,

Sergio

**Comment by pllim** [comment]
Hi. Can you please provide the traceback? How exactly are you trying to run/open it? What OS and Python/Jupyter versions?

**Comment by sergiohoyer** [comment]
OS linux, python 3.7 , ipython 7.6.1
When visiting github:
https://github.com/spacetelescope/notebooks/blob/master/notebooks/MAST/TESS/beginner_astroquery_dv/beginner_astroquery_dv.ipynb    

I got the message "something went wrong"


When running locally (jupyter core 4.5, jupyter-notebook 6) I got:
Unreadable Notebook: beginner_astroquery_dv.ipynb NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang...")

**Comment by scfleming** [comment]
The "something went wrong" message is an error with GitHub not displaying the contents of a notebook in your browser.  But even if GitHub does fix that, it won't allow you to run the notebook in the browser, just see the contents.

The second error does seem like a problem though, potentially with the notebook itself.  Just to make sure, did you check out the Github repostiory with a "git clone" command, or did you attempt to save the file from the browser to your disk?  If you saved the file, depending on how you did it, there might be HTML in there and not be a real .ipynb file.

**Comment by sergiohoyer** [comment]
Hi, 
Github shows me the content of the notebook now! no more "something went wrong"
Regarding the second error,it is very likely that was related on how I downloaded the file.  I will try with the clone command later.  But for the moment I can survive with the content showed by Github.
Thanks!

**Comment by scfleming** [comment]
OK great, I will close this Issue for now, but if you have any questions about how to git clone the repo to run the notebook, don't hesitate to contact us!

**Comment by scfleming** [comment]
@pllim @ceb8 This can be closed as resolved (I don't seem to have the necessary permissions to close it myself).
