### ISSUE TITLE
"$" symbol missing in Setup.ipynb

### ISSUE THREAD

**Issue by jmao2014** [spacetelescope/notebooks#170]
notebooks/notebooks/COS/Setup/Setup.ipynb
Section 3.2, the last line
alias lref='{HOME}/crds_cache/references/hst/cos'

It should be 
alias lref='${HOME}/crds_cache/references/hst/cos'

**Comment by pllim** [comment]
Good catch. Do you want to open a PR? :)

**Comment by jmao2014** [comment]
Yep, see PR #172 : )
