### ISSUE TITLE
An option to overwrite existing file with costools.timefilter.TimelineFilter

### ISSUE THREAD

**Issue by jmao2014** [spacetelescope/notebooks#171]
Hi, 

May I suggest adding a bool-type parameter "clobber" to costools.timefilter.TimelineFilter so that the output file can be overwritten. Currently, if I repeat the analysis without deleting the file created by previous runs, I will encounter a RuntimeError. 

Junjie

**Comment by pllim** [comment]
cc @nkerman

**Comment by nkerman** [comment]
Hi @jmao2014 @pllim - yes that is definitely something that we would like to be able to add to COSTools. Unfortunately, I can't offer any sort of *timeline* on that feature. 

For now, I can offer a brief code snippet to check if the output files exist yet, and delete them if they do. This would be run immediately before the TimelineFilter command. You could even put it at the top of the same cell. It's no replacement for implementing overwrite functionality, but hopefully it will be helpful for now.

```python
if os.path.exists(intermediate_dir / "filtered_corrtag_a.fits"): # Check if we've already created a filtered file
    os.remove(intermediate_dir / "filtered_corrtag_a.fits")       #   if so, delete it so we can run TimelineFilter
if os.path.exists(intermediate_dir / "filtered_corrtag_b.fits"): #   Do the above with rawtag_b file
    os.remove(intermediate_dir / "filtered_corrtag_b.fits")
```

**Comment by jmao2014** [comment]
No worries, I have implemented similar lines in my code to remove existing files.

**Comment by nkerman** [comment]
Great, I will close this issue, and add some similar advice into the Notebook.
Thank you for raising this issue, @jmao2014
