### ISSUE TITLE
Check IMAGETYP first before applying filtering

### ISSUE THREAD

**Issue by jmao2014** [spacetelescope/notebooks#173]
In the notebook on "Filtering out COS Data taken during the Day or Night", the user might wonder whether the observation they would like to analyze should remove time intervals with positive solar altitudes. Hence, maybe add some descriptions to check the fits header keyword IMAGETYP first somewhere in Section 1.1?

**Comment by nkerman** [comment]
Hi @jmao2014 - are you talking about checking `IMAGETYP` to verify that the data was taken in TIME-TAG mode? I'm not entirely sure what you're getting at? Would you mind clarifying? Thank you!

**Comment by jmao2014** [comment]
Hi @nkerman, COS has two modes of data collection (TIME-TAG and ACCUM). In the exemplary notebook, the observation lbry01i6q is taken with the TIME-TAG mode. When dealing with other observations, one might want to check first whether the data is taken with the TIME-TAG mode. Does this make sense?
