### ISSUE TITLE
CalCOS 3.4 is incompatible with astroconda environments

### ISSUE THREAD

**Issue by nkerman** [spacetelescope/notebooks#193]
Astroconda does not seem to be able to solve for environments with Python > 3.7 but CalCOS now needs Python >=3.8 . This is a conflict for all COS Notebooks which need to use CalCOS: 
* CalCOS
* Extract
* DayNight
* SplitTag
 as well as 
* Setup.ipynb 
 which doesn't run CalCOS, but describes creating an astroconda environment. 

The best solution would be getting astroconda working for Python >=3.8. However, in the interim, the CalCOS Notebook has already been updated to not use astroconda. 

We need to consider updating the other Notebooks to at least point to this solution.

**Comment by stscirij** [comment]
The difficulty of solving the dependencies for Python > 3.8 in astroconda is the main reason we are moving away from astroconda, so getting astroconda working for Python >= 3.8 is probably a non-starter.  The steps laid out in the new version of the Calcos notebook in #192 look good and I'd recommend updating Setup as the highest priority.

**Comment by nkerman** [comment]
This has been resolved via an astroconda workaround via PR #194.
