### ISSUE TITLE
Write a contributing guide

### ISSUE THREAD

**Issue by arfon** [spacetelescope/notebooks#2]
We need to make it very obvious how people can contribute to this repository (i.e. a `CONTRIBUTING.md`). This should be some kind of guide (in this repo) that (at least):

- Links to the style guide
- Explains the CI/testing philosophy
- Makes it clear who the maintainers are

**Comment by eteq** [comment]
@arfon - do you think this is closed now? Or alternatively, we might close this and make a second issue along the lines of "improve contributing guide" if what's there is only partly sufficient?

**Comment by arfon** [comment]
@eteq yeah, I think this can be closed? 

> - Makes it clear who the maintainers are

We should make this a priority ☝️
