### ISSUE TITLE
Show a per-notebook table of contents

### ISSUE THREAD

**Issue by eteq** [spacetelescope/notebooks#29]
Right now to get a table of contents, the notebook creator has to do so manually with built-in HTML links.  This can be distracting, is brittle (a later modifier may not think to update the TOC), and isn't guaranteed to be compatible with future browser interfaces (e.g. Jupyter Lab). 

A safer bet is to have a generated TOC that infers the structure from the form of the headers.  I'm taking inspiration from the sphinx-based approach to building notebooks:
![image](https://user-images.githubusercontent.com/346587/49747206-e565f080-fc70-11e8-9789-074c31856949.png)
(from http://www.astropy.org/astropy-tutorials/rst-tutorials/UVES.html)

There are two possible implementation paths I see:
1. Have some javascript that at-page-load figures out the structure from the headers and generates the TOC on the fly. (Probably a bit simpler, but requires javascript/at-load-time modification of the page)
2. Add the TOC to the jinja2 template for the pages.  This would need to either get passed in the header-structure, or need some extra logic in `nbpages` to read a "first round" HTML for headers which then gets re-processed. (static in the page, but probably a bit more complex to code up).

I think the fastest approach might be to start with 1, and then try to implement 2 when there's a bit more time.

Assigning myself, although if anyone else wants to take a crack at it I'm all ears!

**Comment by obviousrebel** [comment]
<img width="1467" alt="screen shot 2019-02-13 at 4 55 40 pm" src="https://user-images.githubusercontent.com/20295433/52746763-459a4b00-2fb0-11e9-97a1-42ee1444354b.png">

Playing around with doing this at page load, a little rough (I'm not the best with CSS) but let me know if you think this is a viable solution (for now) @eteq

**Comment by eteq** [comment]
@obviousrebel - I definitely agree using an extension is better if possible... but can you clarify if this is working in the HTML view on the live build?  That extension looks like it's meant for use inside the notebook, and it's not clear if it will work in the static HTML form? (Although *both* would be even better if that's what's happening!)

I have quibbles about the style, but I think we don't necessarily need to dwell on that here.  I sympathize with not being friends with CSS, but there are other people we could ping who can focus on that once this framework is in place?
