### ISSUE TITLE
Identify maintainers

### ISSUE THREAD

**Issue by arfon** [spacetelescope/notebooks#3]
We need to identify a core staff of STScI people who will help would-be contributors make successful contributions to this repository.

Suggested maintainers:

- DMD staff
- DSMO staff
- RIAB folks

**Comment by pllim** [comment]
As per discussions with @hcferguson and @eteq today, @eteq is going to document the ownership guide for the notebooks.

**Comment by eteq** [comment]
I'm going to declare victory here, as we have several maintainers now.  Obviously it's an on-going project, but I'm going to interpret this issue as the "initial maintainers".
