### ISSUE TITLE
Try to suppress the "CRDS - INFO" messages from drizzlepac notebooks

### ISSUE THREAD

**Issue by eteq** [spacetelescope/notebooks#43]
I just noticed that after I merged drizzlepac-related notebook, the build logs have become harder to read because a bunch of lines that start with ``CRDS - INFO``.  As an example see: https://travis-ci.org/spacetelescope/notebooks/jobs/475847563#L986 . This isn't the end of the world, but it's pretty distracting in the build logs and makes it hard to see where "real" problems might be appearing. So if there's some way to just hide these warnings, at least in Travis, that would be better.

@catherine-martlin or @tddesjardins, any ideas on how this might be accomplished? (I don't know CRDS that well...)

**Comment by pllim** [comment]
@jaytmiller would know.

**Comment by obviousrebel** [comment]
@eteq I believe this can be done by adding --verbosity=0 to the crds subprocess in the notebook file. Tested locally and it removes them.

```
  subprocess.check_output('crds bestrefs --verbosity=0 --files ua0605*_c0m.fits --sync-references=1 --update-bestrefs', shell=True)
```
