### ISSUE TITLE
Travis CI is broken?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/notebooks#49]
The deploy portion of https://travis-ci.org/spacetelescope/notebooks/builds/476275730 shows a red status, as a result the whole project CI status is red. 

Also see https://jira.stsci.edu/browse/JUSI-24

**Comment by pllim** [comment]
Thanks to @obviousrebel who moved CI to CircleCI, so can we remove `.travis.yml` now and disable Travis webhook, @eteq ?

**Comment by pllim** [comment]
Also need to replace Travis badge in README with CircleCI badge.

https://circleci.com/docs/2.0/status-badges/

**Comment by obviousrebel** [comment]
@eteq @pllim [PR to cleanup travis](https://github.com/spacetelescope/notebooks/pull/70) Created a small PR to remove travis and update status badge. After merging that I believe we can close this issue.
