### ISSUE TITLE
Tag with "mast"

### ISSUE THREAD

**Issue by scfleming** [spacetelescope/notebooks#52]
Could this repo get a tag called "mast" so that a URL that looks like https://github.com/search?q=topic%3Amast+org%3Aspacetelescope would allow this to show up as public software relevant for MAST users?

**Comment by pllim** [comment]
Only @eteq can do this. I don't have admin access.

**Comment by eteq** [comment]
Tag added. (see https://github.com/topics/mast).  A bit oddly, @scfleming's search doesn't seem to be working but I think it might be a temporary cache thing.
