### ISSUE TITLE
svg icon files don't show up in browser

### ISSUE THREAD

**Issue by scfleming** [spacetelescope/notebooks#54]
On a Mac at least, use of the .svg version of the STScI logo does not show up when viewing the notebook in GitHub on a browser (shows broken image).  Use of the .svg logo does show up fine when running the notebook locally, so maybe a GitHub issue?

Should I continue to use the smaller .svg logo for notebooks, or switch back to the PNG version?

**Comment by pllim** [comment]
> viewing the notebook in GitHub on a browser

Is that a supported use case, @eteq ?

**Comment by pllim** [comment]
Perhaps related: https://github.community/t5/How-to-use-Git-and-GitHub/Embedding-a-SVG/m-p/2365#M756

**Comment by pllim** [comment]
No longer an issue. See #82
