### ISSUE TITLE
So many copies of logo images

### ISSUE THREAD

**Issue by pllim** [spacetelescope/notebooks#71]
Looks like every notebook has its own PNG or SVG logo file, but they are all effectively the same logo! Is this really necessary?! Can we not have only *one* logo file to be shared by all the notebooks in this repo?

```
$ find ./ -name "stsci*.png" | wc -l
14
$ find ./ -name "stsci*.svg" | wc -l
5
```

```
$ ls -lh notebooks/MAST/TESS/interm_tesscut_dss_overlay/stsci_pri_combo_mark_horizonal_white_bkgd.png
-rw-r--r--. 1 ... 112K Mar 18 15:59 .../stsci_pri_combo_mark_horizonal_white_bkgd.png
```

```
$ ls -lh notebooks/MAST/K2/K2_TPF/stsci_pri_combo_mark_horizonal_white_bkgd.svg
-rw-r--r--. 1 ... 7.8K Mar 18 15:59 .../stsci_pri_combo_mark_horizonal_white_bkgd.svg
```

**Comment by pllim** [comment]
FWIW, this renders properly for me locally:
```html
<img style="float: right;" src="https://static1.squarespace.com/static/51815eaae4b0841085acb675/t/57220256555986178fe78612/1461846625662/stsci_pri_combo_mark_horizonal_white_bkgd.png?format=300w" alt="stsci_pri_combo_mark_horizonal_white_bkgd" width="200px"/> 
```

**Comment by eteq** [comment]
Hmm, does anyone know the origin of this repetition (@ceb8, @arfon, or @JosieBunnell) ?  I have a hazy memory that there was a reason for it, but I can't recall it now, and @pllim's arguments are persuasive that it's better to share one logo location...

**Comment by arfon** [comment]
There's no good reason for repetition, other than the goal for each notebook to be somewhat self-contained with respect to the visual assets (images/logos). 

What about having a top-level directory in this repository called 'assets' or something similar with these shared items. We can then link to them as @pllim suggests using the raw GitHub URLs e.g.:

```
https://raw.githubusercontent.com/spacetelescope/notebooks/master/notebooks/MAST/TESS/interm_tesscut_astroquery/stsci_pri_combo_mark_horizonal_white_bkgd.png```

**Comment by pllim** [comment]
I would propose that we use https://static1.squarespace.com/static/51815eaae4b0841085acb675/t/57220256555986178fe78612/1461846625662/stsci_pri_combo_mark_horizonal_white_bkgd.png?format=300w directly if that works, as that is the place for official OPO branding resources. If the link ever breaks, it is OPO's job to fix it.

**Comment by arfon** [comment]
> I would propose that we use https://static1.squarespace.com/static/51815eaae4b0841085acb675/t/57220256555986178fe78612/1461846625662/stsci_pri_combo_mark_horizonal_white_bkgd.png?format=300w directly if that works, as that is the place for official OPO branding resources. If the link ever breaks, it is OPO's job to fix it.

Do we know how stable that URL is? Also, how would we know if/when it breaks? I'm inclined to copy the assets (images etc.) we need into this repository so that we can be certain they're working.

**Comment by pllim** [comment]
Fine then, but only **ONE COPY**. *There can be only one!*

**Comment by arfon** [comment]
> Fine then, but only ONE COPY. There can be only one!

Deal.

**Comment by pllim** [comment]
Update: `assets` added in #82 (thanks, @arfon !). Duplicate logo files and affected notebooks still need to be cleaned up.
