### ISSUE TITLE
CircleCI doesn't merge with master

### ISSUE THREAD

**Issue by eteq** [spacetelescope/notebooks#76]
A property that circleCI PRs have is that they are not, in general, merged into master before the tests get run, unlike e.g. Travis.   spacetelescope/notebooks#75 shows an example of why this might not be desirable (e.g. a missing/broken `.circleci/config.yml` in the branch that was fixed in master).

I suspect this could be ameliorated by explicitly adding a "merge master into this checkout" step before the run/convert steps get run.  The tricky part there is a flexible enough definition of "which master" - i.e., it has to do the right thing based on what the PR's "head" is, not just always assume its actually spacetelescope/master.  There's almost certainly a way to do this using some combination of the circleci-injected environment variables and the github API, but I don't know what that way is in detail.  It also might not work for changes in the circleci config (i.e., #75...), as I'm guessing CircleCI parses that before doing other steps.  But maybe we just accept that as a fact of life and at least catch other merge-into-master changes?

**Comment by pllim** [comment]
The problem was solved for me when I rebased my branch. Future PR made with branch that is derived from latest master won't have this problem. I propose we close this as won't fix. A rebase on older PRs would solve the problem.

**Comment by obviousrebel** [comment]
This is/has been a feature request for CircleCI. I did find this snippet as a temp solution:
```
checkout:
  post:
    - |
        if [[ -n "${CIRCLE_PR_NUMBER}" ]]
        then
            # Update PR refs for testing.
            FETCH_REFS="${FETCH_REFS} +refs/pull/${CIRCLE_PR_NUMBER}/head:pr/${CIRCLE_PR_NUMBER}/head"
            FETCH_REFS="${FETCH_REFS} +refs/pull/${CIRCLE_PR_NUMBER}/merge:pr/${CIRCLE_PR_NUMBER}/merge"

            # Retrieve the refs
            git fetch -u origin ${FETCH_REFS}

            # Checkout PR merge ref.
            git checkout -qf "pr/${CIRCLE_PR_NUMBER}/merge"

            # Test for *some* merge conflicts.
            git branch --merged | grep "pr/${CIRCLE_PR_NUMBER}/head" > /dev/null
        fi
```

**Comment by pllim** [comment]
Asking author to rebase once in a while won't kill them, so closing as won't fix.
