### ISSUE TITLE
TST: CircleCI to run subsequent notebooks even if previous one fails

### ISSUE THREAD

**Issue by pllim** [spacetelescope/notebooks#83]
When CircleCI is enabled for a pull request, a significant of the failures stemmed from other unrelated notebooks (e.g., #80 and timeouts from MAST queries). But really the author is interested to see if the new notebook added in the PR can pass CI. I propose CircleCI does not just stop when it encounters the first failure, but to keep going until the end, and then report what failed and what didn't.

**OR** CircleCI should just run that one notebook without author having to manually exclude the rest. But that also means if the PR messes up requirements for the other notebooks, we won't know.

**Comment by obviousrebel** [comment]
@pllim This has to be implemented in nbpages, these are waiting review there:
[nbpages PR for only checking changed notebooks](https://github.com/eteq/nbpages/pull/6)
[nbpages PR for report generation (if a notebook fails, continues but logs it)](https://github.com/eteq/nbpages/pull/4)
