### ISSUE TITLE
Directory Organization

### ISSUE THREAD

**Issue by tddesjardins** [spacetelescope/notebooks#90]
Getting ready to submit a few HST/ACS notebooks, but wanted to ask how we want these organized. Thinking about it, it makes sense to me to have an HST mission directory with subdirectories for ACS, WFC3, etc. under it (similar for JWST). Alternatively, if we don't want to go that route for whatever reason, I would suggest enforcing having directory names like HST-ACS, JWST-MIRI, etc. so that all the instrument-specific directories are grouped together in the directory structure. @eteq any thoughts?

**Comment by pllim** [comment]
Well, @samanthalh contributed to the DrizzlePac ones, which would be affected by this re-organization. Also maybe some from ASB, so cc @ceb8 too.

For the existing one, maybe the ship has sailed. If that is the case, will this only affect future notebooks? I did add a JWST directory in #75 but it is not merged yet.

**Comment by tddesjardins** [comment]
I think DrizzlePac is fine to leave separate. It's HST only, but then again it's cross-instrument, so it would still need to be on its own even in an HST area. I think it's fine to leave it simply as DrizzlePac. Same for MAST, if it's talking about MAST products in general.

**Comment by pllim** [comment]
Well, if it does not affect anything already in the repo, then #75 would set the precedent of what you discussed. We all good?

**Comment by tddesjardins** [comment]
We're good! :)
