### ISSUE TITLE
Update gitignore to include .fits, etc.

### ISSUE THREAD

**Issue by obviousrebel** [spacetelescope/notebooks#97]
Would it be beneficial to update .gitignore to include some commonly downloaded file extensions? Such as:
*.fits
*.fits.gz
*.zip

Perhaps this can be another safeguard in addition to [WIP large committed file checking](https://github.com/eteq/nbpages/pull/8) to help prevent accidental committing of data files.

Another added benefit would be the ability to use `git clean -fX` prior to the persist workspace and store_artifact steps in circleCI. This would prevent these unnecessary files from being archived and stored speeding up the builds.

**Comment by pllim** [comment]
`.gitignore` is the way to go, but I would advise we don't make it as general as `*.fits` because there might come a time when we need to include a tiny FITS file or something in the repo.

**Comment by obviousrebel** [comment]
Maybe we could include *.fits in the .gitignore and state in the documentation that if it is absolutely necessary to include a data file with a notebook (tried all alternatives in the contributing/style guide for data files) then add `!specific_fits_file.fits` to the .gitignore for the PR to add the notebook.

**Comment by pllim** [comment]
Sounds reasonable. What do you think, @eteq?

**Comment by laurenmarietta** [comment]
I added a `.gitignore` file within `notebooks/notebooks` just for myself, to clean up the `git status` messages. Here is what I put in there, if it's helpful:
```
exec_*.ipynb
*.html
*.fits
*.coo
*.match
*.log
*.png
!DrizzlePac/sky_matching/MDRIZSKY_Values.png
*.list
!DrizzlePac/align_sparse_fields/input_flc.list
!DrizzlePac/sky_matching/drz.list
```

**Comment by pllim** [comment]
@laurenmarietta , are you interested to put in a PR for this, since you already have the solution? Thanks!

**Comment by laurenmarietta** [comment]
Of course, will do!
